### ISSUE TITLE
Error installing pg

### ISSUE THREAD

**Issue by tech-vsilva** [sous-chefs/postgresql#427] opened 2017-04-13 09:28 UTC
### Cookbook version
6.1.1

### Chef-client version
12.19.36

### Platform Details
Ubuntu 16

### Scenario:
Use the postgresql cookbook without any errors.

### Steps to Reproduce:
Just import the cookbook and a dependency and converge.

### Expected Result:
Converge the cookbook without any errors.

### Actual Result:

```
Recipe: postgresql::ruby
  * apt_package[postgresql-client-9.5, libpq-dev] action install[2017-04-13T11:13:13+02:00] INFO: Processing apt_package[postgresql-client-9.5, libpq-dev] action install (postgresql::ruby line 55)
 (up to date)
  * chef_gem[pg] action install[2017-04-13T11:13:13+02:00] INFO: Processing chef_gem[pg] action install (postgresql::ruby line 60)
[/root/.chefdk/gem/ruby/2.3.0/specifications/pg-0.20.0.gemspec] isn't a Gem::Specification (NilClass instead).
[/root/.chefdk/gem/ruby/2.3.0/specifications/pg-0.20.0.gemspec] isn't a Gem::Specification (NilClass instead).
[/root/.chefdk/gem/ruby/2.3.0/specifications/pg-0.20.0.gemspec] isn't a Gem::Specification (NilClass instead).
[/root/.chefdk/gem/ruby/2.3.0/specifications/pg-0.20.0.gemspec] isn't a Gem::Specification (NilClass instead).
[/root/.chefdk/gem/ruby/2.3.0/specifications/pg-0.20.0.gemspec] isn't a Gem::Specification (NilClass instead).
[/root/.chefdk/gem/ruby/2.3.0/specifications/pg-0.20.0.gemspec] isn't a Gem::Specification (NilClass instead).
[/root/.chefdk/gem/ruby/2.3.0/specifications/pg-0.20.0.gemspec] isn't a Gem::Specification (NilClass instead).

    
    ================================================================================
    Error executing action `install` on resource 'chef_gem[pg]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of /opt/chefdk/embedded/bin/gem install pg -q --no-rdoc --no-ri -v "0.20.0" ----
    STDOUT: Building native extensions.  This could take a while...
    STDERR: [/root/.chefdk/gem/ruby/2.3.0/specifications/pg-0.20.0.gemspec] isn't a Gem::Specification (NilClass instead).
    [/root/.chefdk/gem/ruby/2.3.0/specifications/pg-0.20.0.gemspec] isn't a Gem::Specification (NilClass instead).
    [/root/.chefdk/gem/ruby/2.3.0/specifications/pg-0.20.0.gemspec] isn't a Gem::Specification (NilClass instead).
    [/root/.chefdk/gem/ruby/2.3.0/specifications/pg-0.20.0.gemspec] isn't a Gem::Specification (NilClass instead).
    [/root/.chefdk/gem/ruby/2.3.0/specifications/pg-0.20.0.gemspec] isn't a Gem::Specification (NilClass instead).
    [/root/.chefdk/gem/ruby/2.3.0/specifications/pg-0.20.0.gemspec] isn't a Gem::Specification (NilClass instead).
    [/root/.chefdk/gem/ruby/2.3.0/specifications/pg-0.20.0.gemspec] isn't a Gem::Specification (NilClass instead).
    WARNING:  You don't have /root/.chefdk/gem/ruby/2.3.0/bin in your PATH,
    	  gem executables will not run.
    ERROR:  Error installing pg:
    	ERROR: Failed to build gem native extension.
    
        current directory: /root/.chefdk/gem/ruby/2.3.0/gems/pg-0.20.0/ext
    /opt/chefdk/embedded/bin/ruby -r ./siteconf20170413-17107-1jr4uhz.rb extconf.rb
    checking for pg_config... yes
    Using config values from /usr/bin/pg_config
    checking for libpq-fe.h... yes
    checking for libpq/libpq-fs.h... yes
    checking for pg_config_manual.h... yes
    checking for PQconnectdb() in -lpq... no
    checking for PQconnectdb() in -llibpq... no
    checking for PQconnectdb() in -lms/libpq... no
    Can't find the PostgreSQL client library (libpq)
    *** extconf.rb failed ***
    Could not create Makefile due to some reason, probably lack of necessary
    libraries and/or headers.  Check the mkmf.log file for more details.  You may
    need configuration options.
    
    Provided configuration options:
    	--with-opt-dir
    	--with-opt-include
    	--without-opt-include=${opt-dir}/include
    	--with-opt-lib
    	--without-opt-lib=${opt-dir}/lib
    	--with-make-prog
    	--without-make-prog
    	--srcdir=.
    	--curdir
    	--ruby=/opt/chefdk/embedded/bin/$(RUBY_BASE_NAME)
    	--with-pg
    	--without-pg
    	--enable-windows-cross
    	--disable-windows-cross
    	--with-pg-config
    	--without-pg-config
    	--with-pg_config
    	--without-pg_config
    	--with-pg-dir
    	--without-pg-dir
    	--with-pg-include
    	--without-pg-include=${pg-dir}/include
    	--with-pg-lib
    	--without-pg-lib=${pg-dir}/lib
    	--with-pqlib
    	--without-pqlib
    	--with-libpqlib
    	--without-libpqlib
    	--with-ms/libpqlib
    	--without-ms/libpqlib
    
    To see why this extension failed to compile, please check the mkmf.log which can be found here:
    
      /root/.chefdk/gem/ruby/2.3.0/extensions/x86_64-linux/2.3.0/pg-0.20.0/mkmf.log
    
    extconf failed, exit code 1
    
    Gem files will remain installed in /root/.chefdk/gem/ruby/2.3.0/gems/pg-0.20.0 for inspection.
    Results logged to /root/.chefdk/gem/ruby/2.3.0/extensions/x86_64-linux/2.3.0/pg-0.20.0/gem_make.out
    ---- End output of /opt/chefdk/embedded/bin/gem install pg -q --no-rdoc --no-ri -v "0.20.0" ----
    Ran /opt/chefdk/embedded/bin/gem install pg -q --no-rdoc --no-ri -v "0.20.0" returned 1
    
    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/postgresql/recipes/ruby.rb:60:in `rescue in from_file'
    /var/chef/cache/cookbooks/postgresql/recipes/ruby.rb:22:in `from_file'
    /var/chef/cache/cookbooks/database/recipes/postgresql.rb:20:in `from_file'
    /var/chef/cache/cookbooks/anevis_jenkins/recipes/requirements.rb:20:in `from_file'
    /var/chef/cache/cookbooks/anevis_jenkins/recipes/default.rb:13:in `from_file'
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/postgresql/recipes/ruby.rb
    
     60:     chef_gem 'pg' do
     61:       compile_time true
     62:       version node['postgresql']['pg_gem']['version'] if node['postgresql']['pg_gem']['version']
     63:     end
     64:   rescue Gem::Installer::ExtensionBuildError, Mixlib::ShellOut::ShellCommandFailed => e
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/postgresql/recipes/ruby.rb:60:in `rescue in from_file'
    
    chef_gem("pg") do
      package_name "pg"
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :chef_gem
      cookbook_name "postgresql"
      recipe_name "ruby"
      compile_time true
      gem_binary "/opt/chefdk/embedded/bin/gem"
    end
    
    Platform:
    ---------
    x86_64-linux
    
[2017-04-13T11:13:14+02:00] WARN: Failed to properly build pg gem. Forcing properly linking and retrying (omnibus fix)
  * execute[generate pg gem Makefile] action run[2017-04-13T11:13:14+02:00] INFO: Processing execute[generate pg gem Makefile] action run (postgresql::ruby line 94)

    [execute] checking for pg_config... yes
              Using config values from /usr/bin/pg_config
              checking for libpq-fe.h... yes
              checking for libpq/libpq-fs.h... yes
              checking for pg_config_manual.h... yes
              checking for PQconnectdb() in -lpq... yes
              checking for PQconnectionUsedPassword()... yes
              checking for PQisthreadsafe()... yes
              checking for PQprepare()... yes
              checking for PQexecParams()... yes
              checking for PQescapeString()... yes
              checking for PQescapeStringConn()... yes
              checking for PQescapeLiteral()... yes
              checking for PQescapeIdentifier()... yes
              checking for PQgetCancel()... yes
              checking for lo_create()... yes
              checking for pg_encoding_to_char()... yes
              checking for pg_char_to_encoding()... yes
              checking for PQsetClientEncoding()... yes
              checking for PQlibVersion()... yes
              checking for PQping()... yes
              checking for PQsetSingleRowMode()... yes
              checking for PQconninfo()... yes
              checking for PQsslAttribute()... yes
              checking for rb_encdb_alias()... yes
              checking for rb_enc_alias()... no
              checking for rb_thread_call_without_gvl()... yes
              checking for rb_thread_call_with_gvl()... yes
              checking for rb_thread_fd_select()... yes
              checking for rb_w32_wrap_io_handle()... no
              checking for rb_str_modify_expand()... yes
              checking for rb_hash_dup()... yes
              checking for PGRES_COPY_BOTH in libpq-fe.h... yes
              checking for PGRES_SINGLE_TUPLE in libpq-fe.h... yes
              checking for PG_DIAG_TABLE_NAME in libpq-fe.h... yes
              checking for struct pgNotify.extra in libpq-fe.h... yes
              checking for unistd.h... yes
              checking for inttypes.h... yes
              checking for ruby/st.h... yes
              checking for C99 variable length arrays... yes
              creating extconf.h
              creating Makefile
[2017-04-13T11:13:19+02:00] INFO: execute[generate pg gem Makefile] ran successfully
    - execute PATH=$PATH:/usr/pgsql-9.5/bin /opt/chefdk/embedded/bin/ruby extconf.rb
  * execute[make pg gem lib] action run[2017-04-13T11:13:19+02:00] INFO: Processing execute[make pg gem lib] action run (postgresql::ruby line 102)

    [execute] compiling pg_type_map_by_column.c
              compiling pg_binary_decoder.c
              compiling pg_type_map_all_strings.c
              compiling pg_connection.c
              compiling pg_type_map_by_mri_type.c
              compiling pg_text_encoder.c
              compiling pg.c
              compiling pg_text_decoder.c
              compiling pg_result.c
              compiling pg_type_map.c
              compiling pg_copy_coder.c
              compiling pg_type_map_by_class.c
              compiling gvl_wrappers.c
              compiling util.c
              compiling pg_type_map_in_ruby.c
              compiling pg_binary_encoder.c
              compiling pg_type_map_by_oid.c
              compiling pg_coder.c
              compiling pg_errors.c
              linking shared-object pg_ext.so
[2017-04-13T11:13:23+02:00] INFO: execute[make pg gem lib] ran successfully
    - execute make
  * execute[install pg gem lib] action run[2017-04-13T11:13:23+02:00] INFO: Processing execute[install pg gem lib] action run (postgresql::ruby line 109)

    [execute] /usr/bin/install -c -m 0755 pg_ext.so /opt/chefdk/embedded/lib/ruby/site_ruby/2.3.0/x86_64-linux
[2017-04-13T11:13:23+02:00] INFO: execute[install pg gem lib] ran successfully
    - execute make install
  * execute[install pg spec] action run[2017-04-13T11:13:23+02:00] INFO: Processing execute[install pg spec] action run (postgresql::ruby line 116)

    [execute] [/root/.chefdk/gem/ruby/2.3.0/specifications/pg-0.20.0.gemspec] isn't a Gem::Specification (NilClass instead).
              ERROR:  No gem matching './cache/pg-0.20.0.gem (>= 0)' found
    
    ================================================================================
    Error executing action `run` on resource 'execute[install pg spec]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of /opt/chefdk/embedded/bin/gem spec ./cache/pg-0.20.0.gem --ruby > ./specifications/pg-0.20.0.gemspec ----
    STDOUT: 
    STDERR: [/root/.chefdk/gem/ruby/2.3.0/specifications/pg-0.20.0.gemspec] isn't a Gem::Specification (NilClass instead).
    ERROR:  No gem matching './cache/pg-0.20.0.gem (>= 0)' found
    ---- End output of /opt/chefdk/embedded/bin/gem spec ./cache/pg-0.20.0.gem --ruby > ./specifications/pg-0.20.0.gemspec ----
    Ran /opt/chefdk/embedded/bin/gem spec ./cache/pg-0.20.0.gem --ruby > ./specifications/pg-0.20.0.gemspec returned 1
    
    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/postgresql/recipes/ruby.rb:121:in `rescue in rescue in from_file'
    /var/chef/cache/cookbooks/postgresql/recipes/ruby.rb:59:in `rescue in from_file'
    /var/chef/cache/cookbooks/postgresql/recipes/ruby.rb:22:in `from_file'
    /var/chef/cache/cookbooks/database/recipes/postgresql.rb:20:in `from_file'
    /var/chef/cache/cookbooks/anevis_jenkins/recipes/requirements.rb:20:in `from_file'
    /var/chef/cache/cookbooks/anevis_jenkins/recipes/default.rb:13:in `from_file'
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/postgresql/recipes/ruby.rb
    
    116:     spec_installer = execute 'install pg spec' do
    117:       command "#{gem_exec} spec ./cache/#{gem_name}.gem --ruby > ./specifications/#{gem_name}.gemspec"
    118:       cwd File.join(gem_dir, '..', '..')
    119:       action :nothing
    120:     end
    121:     spec_installer.run_action(:run)
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/postgresql/recipes/ruby.rb:116:in `rescue in rescue in from_file'
    
    execute("install pg spec") do
      action [:nothing]
      retries 0
      retry_delay 2
      default_guard_interpreter :execute
      command "/opt/chefdk/embedded/bin/gem spec ./cache/pg-0.20.0.gem --ruby > ./specifications/pg-0.20.0.gemspec"
      backup 5
      cwd "/root/.chefdk/gem/ruby/2.3.0/gems/pg-0.20.0/../.."
      returns 0
      user nil
      declared_type :execute
      cookbook_name "postgresql"
      recipe_name "ruby"
    end
    
    Platform:
    ---------
    x86_64-linux
    
  
  ================================================================================
  Recipe Compile Error in /var/chef/cache/cookbooks/anevis_jenkins/recipes/default.rb
  ================================================================================
  
  Mixlib::ShellOut::ShellCommandFailed
  ------------------------------------
  execute[install pg spec] (postgresql::ruby line 116) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
  ---- Begin output of /opt/chefdk/embedded/bin/gem spec ./cache/pg-0.20.0.gem --ruby > ./specifications/pg-0.20.0.gemspec ----
  STDOUT: 
  STDERR: [/root/.chefdk/gem/ruby/2.3.0/specifications/pg-0.20.0.gemspec] isn't a Gem::Specification (NilClass instead).
  ERROR:  No gem matching './cache/pg-0.20.0.gem (>= 0)' found
  ---- End output of /opt/chefdk/embedded/bin/gem spec ./cache/pg-0.20.0.gem --ruby > ./specifications/pg-0.20.0.gemspec ----
  Ran /opt/chefdk/embedded/bin/gem spec ./cache/pg-0.20.0.gem --ruby > ./specifications/pg-0.20.0.gemspec returned 1
  
  Cookbook Trace:
  ---------------
    /var/chef/cache/cookbooks/postgresql/recipes/ruby.rb:121:in `rescue in rescue in from_file'
    /var/chef/cache/cookbooks/postgresql/recipes/ruby.rb:59:in `rescue in from_file'
    /var/chef/cache/cookbooks/postgresql/recipes/ruby.rb:22:in `from_file'
    /var/chef/cache/cookbooks/database/recipes/postgresql.rb:20:in `from_file'
    /var/chef/cache/cookbooks/anevis_jenkins/recipes/requirements.rb:20:in `from_file'
    /var/chef/cache/cookbooks/anevis_jenkins/recipes/default.rb:13:in `from_file'
  
  Relevant File Content:
  ----------------------
  /var/chef/cache/cookbooks/postgresql/recipes/ruby.rb:
  
  114:      lib_installer.run_action(:run)
  115:  
  116:      spec_installer = execute 'install pg spec' do
  117:        command "#{gem_exec} spec ./cache/#{gem_name}.gem --ruby > ./specifications/#{gem_name}.gemspec"
  118:        cwd File.join(gem_dir, '..', '..')
  119:        action :nothing
  120:      end
  121>>     spec_installer.run_action(:run)
  122:  
  123:      Chef::Log.warn 'Installation of pg gem successful!'
  124:    end
  125:  end
  126:  
  
  Platform:
  ---------
  x86_64-linux
  
  
  Running handlers:
[2017-04-13T11:13:23+02:00] ERROR: Running exception handlers
  Running handlers complete
[2017-04-13T11:13:23+02:00] ERROR: Exception handlers complete
  Chef Client failed. 7 resources updated in 20 seconds
[2017-04-13T11:13:23+02:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2017-04-13T11:13:23+02:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-04-13T11:13:23+02:00] ERROR: execute[install pg spec] (postgresql::ruby line 116) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /opt/chefdk/embedded/bin/gem spec ./cache/pg-0.20.0.gem --ruby > ./specifications/pg-0.20.0.gemspec ----
STDOUT: 
STDERR: [/root/.chefdk/gem/ruby/2.3.0/specifications/pg-0.20.0.gemspec] isn't a Gem::Specification (NilClass instead).
ERROR:  No gem matching './cache/pg-0.20.0.gem (>= 0)' found
---- End output of /opt/chefdk/embedded/bin/gem spec ./cache/pg-0.20.0.gem --ruby > ./specifications/pg-0.20.0.gemspec ----
Ran /opt/chefdk/embedded/bin/gem spec ./cache/pg-0.20.0.gem --ruby > ./specifications/pg-0.20.0.gemspec returned 1
[2017-04-13T11:13:23+02:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

```

**Comment by shortdudey123** [comment] 2017-04-13 18:59
Just a quick skim... it looks like this is probably the cause
`Can't find the PostgreSQL client library (libpq)`

**Comment by teknofire** [comment] 2017-05-04 21:52
I'm not able to duplicate this error, @valterhenrique does by chance your cookbook install the chefdk at some point during the converge?  It looks like it's trying pull some gems from `/root/.chefdk/` when I would expect it to be using a `/opt/chef/embedded/`

**Comment by sebaacuna** [comment] 2017-05-16 16:06
I'm having this same problem using `chef-solo`. I did install the ChefDK manually on the server beforehand. @teknofire any way I can coerce chef to use the `/opt/chef/embedded/` instead of `/root/.chefdk` if this were the problem?

**Comment by valterhenrique** [comment] 2017-05-17 10:03
@teknofire Unfortunately, I'm not working with this project anymore and I can't give you more details about it. Should I close this issue ? Thanks!

**Comment by teknofire** [comment] 2017-05-17 17:18
lets keep it open for now, I'm going to see if I can replicate the issue with chefdk installed.

**Comment by sekrett** [comment] 2017-06-29 13:53
I also cannot install pg gem for Chef on Debian 8. If I do `gem install pg` for system Ruby it works, but if I do `/opt/chef/embedded/bin/gem install pg` it fails:

```
checking for PQconnectdb() in -lpq... no
checking for PQconnectdb() in -llibpq... no
checking for PQconnectdb() in -lms/libpq... no
Can't find the PostgreSQL client library (libpq)
```

**Comment by alexbel** [comment] 2017-07-29 02:37
`apt-get -y install linux-headers-$(uname -r) build-essential` did the trick. At least in my case.

**Comment by damacus** [comment] 2017-10-28 20:49
@alexbel thanks for the fix! Closing issue

**Comment by sekrett** [comment] 2017-10-29 12:46
@damacus , if installing kernel headers fixes the problem, I think the cookbook should install it automatically. Chef is often executed on empty OSes.

**Comment by damacus** [comment] 2017-10-29 18:59
Agreed.

I'm not seeing this problem with vanilla Debian 9 without build essentials though.

I'll leave open for me to debug tomorrow

**Comment by damacus** [comment] 2017-12-28 16:08
Related to #462

**Comment by damacus** [comment] 2018-01-22 23:26
Closing in favour of tracking in #462

**Closed by damacus** 2018-01-22 23:26 UTC
Labels: Status: Blocked, Type: Bug
