### ISSUE TITLE
Wrong platform_family check in ruby recipe

### ISSUE THREAD

**Issue by dmlb2000** [sous-chefs/postgresql#422] opened 2017-03-14 21:52 UTC
### Cookbook version
v5.2.0

### Chef-client version
12.14.89

### Platform Details
CentOS 7.3

### Scenario:
Trying to include database cookbook and build the `pg` gem against the pgdg version of postgresql...

### Steps to Reproduce:
`include_recipe 'postgresql::ruby'` then try to use the database cookbook enabled with postgresql in the same recipe.

### Expected Result:
Expected the `pg` ruby gem to build against the pgdg version of postgres on a CentOS system during the compile phase of the chef-client run.

### Actual Result:
Seems to skip right over enabling the pgdg repository and goes right to a package that doesn't exist.
```
       Recipe: build-essential::default
         * build_essential[install_packages] action install
           * yum_package[autoconf, bison, flex, gcc, gcc-c++, gettext, kernel-devel, make, m4, ncurses-devel, patch] action install (up to date)
            (up to date)
       Recipe: postgresql::ruby
         * yum_package[postgresql94] action install
           * No candidate version available for postgresql94
```

## Note
This didn't happen in v5.1.0 but does happen in v5.2.0.

**Comment by shortdudey123** [comment] 2017-03-16 22:26
Looks like this was a regression created in https://github.com/sous-chefs/postgresql/commit/31fb5b208141dfb998cda9f9fa32c0976ebe32eb

**Comment by shortdudey123** [comment] 2017-03-16 22:28
However, it was already fixed in https://github.com/sous-chefs/postgresql/commit/780a6ea35ca47877540500676f578bd950a3e67a which was captured in the `v6.0.0` release

**Closed by shortdudey123** 2017-03-16 22:28 UTC
Labels: bug
