### ISSUE TITLE
Chef run fails when installing postgresql with a non default data directory - ubuntu

### ISSUE THREAD

**Issue by phcyso** [sous-chefs/postgresql#355] opened 2016-05-18 05:45 UTC
Same issue as #248 which was closed saying 'Resolved as of release 4.0.0'

however nothing changed with a non default data directory on ubuntu 14.
It looks like the redhat code would work fine as it does the initdb steps, but the Debian recipe is missing this.
Trying to run a fresh install on ubuntu fails as it after it updates the config then tries to restart the server which fails as there are no files in the data_directory location.
The gist linked has my fix in it which may be ubuntu specific

https://gist.github.com/phcyso/1ba49f35e487460ebb809bc37d42457a

**Comment by pg1671** [comment] 2016-06-04 15:03
I have a similar problem when trying to change the default data directory on ubuntu .. If I override both dir and data_directory I get the chef created config files created in that directory but the database is still created in /etc/postgresql/9.5/main .. and the configuration is also taken from this location (rather than the chef created ones).

My chef run does not fail though and the database is created.

**Comment by sworisbreathing** [comment] 2016-07-18 01:58
I'm seeing a similar issue on RHEL 6 using a wrapper cookbook. My wrapper attributes file specifies:
```ruby
default['postgresql']['dir'] = '/path/to/custom/dir'
default['postgresql']['config']['data_directory'] = '/path/to/custom/dir'
```
and still postgres is initialized into `/var/lib/pgsql/9.4/data`

I can still see a few calls to `node.set` in [recipes/server.rb](https://github.com/hw-cookbooks/postgresql/blob/a9d2add5291fb0c8735f2af45e5212ca76ef60da/recipes/server.rb#L56) which appears to be what's breaking things (even on RHEL).

As a workaround, I'm now declaring `default` level attributes in my wrapper cookbook, and then explicitly overriding the postgres cookbook's attributes in my wrapper's recipe:

in `wrapper_cookbook/attributes/postgresql.rb`:

```ruby
default['wrapper_cookbook']['postgresql']['dir'] = '/path/to/custom/dir'
default['wrapper_cookbook']['postgresql']['config']['data_directory'] = '/path/to/custom/dir'
```

and then in `wrapper_cookbook/recipes/postgresql.rb`:

```ruby
node.override['postgresql']['dir'] = node['wrapper_cookbook']['postgresql']['dir']
node.override['postgresql']['config']['data_directory'] = node['wrapper_cookbook']['postgresql']['config']['data_directory']
include_recipe 'postgresql::server'
```

With this configuration, I now have postgres initializing into the proper directory, but it's a bit of a klunky workaround...

**Comment by wosc** [comment] 2017-04-12 11:32
I have the same issue, with cookbook version 6.1.1 on Ubuntu-14.

As far as I understand it, the problem is two-fold:
1. The deb package insists on creating a cluster upon installation (which uses the default data directory, not the one we configure for chef). Since the pid file resides inside the data directory, this results in the "invalid pid file" error when `postgresql::server_conf` changes the data directory and then calls restart -- because by then the old, valid pid file can not be found anymore.
2. `postgresql::server_conf` tries to change the config first (and start the server) and _then_ create the cluster, which fails because of course there is no valid cluster setup present yet when the server starts. Also, no recipe ensures that the configure data directory even exists. Also also, #426.

To solve these points, I have re-written `postgresql::server_debian` as follows:
```ruby
include_recipe 'postgresql::client'
package node['postgresql']['server']['packages']

# Remove the default cluster that the deb package insists on creating.
default_data_directory = (
  "/var/lib/postgresql/#{node['postgresql']['version']}/main/")
# Need to stop the server before we change the data directory, since the pid
# file lives inside of it.
execute "Stop deb default server" do
  command "/etc/init.d/postgresql stop"
  only_if { ::File.exists?(default_data_directory) }
end
execute "Remove deb default cluster" do
  command "pg_dropcluster #{node['postgresql']['version']} main"
  only_if { ::File.exists?(default_data_directory) }
end

# Create our actual cluster in the configured data directory.
directory node['postgresql']['config']['data_directory'] do
  owner 'postgres'
  group 'postgres'
  mode '0700'
  action :create
  recursive true
end
execute 'Set locale and Create cluster' do
  command ("export LC_ALL=C; /usr/bin/pg_createcluster " +
    "--datadir=#{node['postgresql']['config']['data_directory']} " +
    "#{node['postgresql']['version']} main ")
  action :run
  not_if { ::File.directory?(
    '/etc/postgresql/' + node['postgresql']['version'] + '/main') }
end

# Now are we ready to configure and start the server.
include_recipe 'postgresql::server_conf'

service 'postgresql' do
  service_name node['postgresql']['server']['service_name']
  supports restart: true, status: true, reload: true
  action [:enable, :start]
end
```

This works for me, when setting `node['postgresql']['config']['data_directory']`.

**Comment by jkarnesPerfectCube** [comment] 2017-07-07 19:21
using the rewrite above by @wosc solved the problem deploying to Ubuntu 16.04 LTS.
:+1: @wosc. Thank you so much.

**Comment by damacus** [comment] 2018-01-22 23:17
Right now we don't support changing the data_dir from each platforms supported directories. 

We'll look into adding support for it after this release has gone out the door. 

Thanks! 
Dan

**Comment by damacus** [comment] 2018-03-23 10:21
Closing for now.

if this is still a problem after the release. We would love a new test suite writing for this and a PR making for the functionality.

**Closed by damacus** 2018-03-23 10:21 UTC
Labels: Priority: Low, Priority: Medium, Type: Feature Request
