### ISSUE TITLE
postgresql_user creation fails against a previously-installed DB instance, due to missing node.run_state['postgresql']['version']

### ISSUE THREAD

**Issue by vanguard737** [sous-chefs/postgresql#538] opened 2018-06-03 02:42 UTC
I have a recipe that creates a postgresql_user, but does not contain a postgresql_server_install resource (the server install is handled in a separate cookbook).  As a result, node.run_state['postgresql']['version'] never gets set, causing the postgresql_user recipe to fail with the errors below.  My workaround is also shown below.  

I'm guessing that the fix for #523  will also fix (or at least affect) this issue as well, correct?

### Cookbook version
7.0.0

### Chef-client version
14.1.12

### Platform Details
Centos 7

### Scenario:
Create a database user against a previously-installed postgres 9.6 instance.

### Steps to Reproduce:
```
# postgresql_server_install resource is *not* referenced in this cookbook
postgresql_user db_user do
  password db_pass
end
```

### Expected Result:
The specified user is created.

### Workaround:
```
ruby_block 'fix_for_postgresql_cookbook_node_run_state' do
  block do
    node.run_state['postgresql'] ||= {}
    node.run_state['postgresql']['version'] = '9.6'
  end
end
```

### Actual Result:
```
Recipe: a29_poolshark::db
  * postgresql_user[poolshark_dev] action create
    * execute[create postgresql user poolshark_dev] action run

      ================================================================================
      Error executing action `run` on resource 'execute[create postgresql user poolshark_dev]'
      ================================================================================

      NoMethodError
      -------------
      undefined method `[]' for nil:NilClass

      Cookbook Trace:
      ---------------
      /tmp/chef/cache/cookbooks/postgresql/libraries/helpers.rb:99:in `data_dir'
      /tmp/chef/cache/cookbooks/postgresql/libraries/helpers.rb:146:in `slave?'
      /tmp/chef/cache/cookbooks/postgresql/resources/user.rb:37:in `block (3 levels) in class_from_file'

      Resource Declaration:
      ---------------------
      suppressed sensitive resource output

      Compiled Resource:
      ------------------
      suppressed sensitive resource output

      System Info:
      ------------
      chef_version=14.1.12
      platform=centos
      platform_version=7.5.1804
      ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
      program_name=/opt/chefdk/bin/chef-client
      executable=/opt/chefdk/bin/chef-client
```

**Comment by damacus** [comment] 2018-06-03 08:28
Ah now we have another good reason to get rid of the run state as per #523

**Comment by damacus** [comment] 2018-06-22 09:28
As 7.1 is a pretty big release already. I'm moving this into 7.2. 

Sorry for the delay on this one, stripping the run state out of PostgreSQL was a slightly tricky one.

**Comment by damacus** [comment] 2018-06-22 21:44
Closing as a duplicate of #523 and tracking there 👍

**Closed by damacus** 2018-06-22 21:44 UTC
Labels: Priority: Medium, Status: Blocked, Type: Bug
